### ISSUE TITLE
Redirect Snap Judgment requests to station page

### ISSUE THREAD

**Issue by kookster** [PRX/proxy.prx.org#38]
As I write this, it occurs to me there are likely other old exchange CMS program pages that should get similar treatment, but this came up for SJ
-----

We have an old exchange cms page for snap judgment, that currently the proxy directs to:

https://github.com/PRX/proxy.prx.org/blob/master/routes/exchange-redirect.js#L72

Instead of redirecting www.prx.org/snap to the exchange, redirect to the station program page within the corp site:

https://www.prx.org/snap -> https://www.prx.org/stations/shows/snap-judgment

and then we can probably just remove/archive the old exchange CMS page for snap.

**Comment by farski** [comment]
Closed by https://github.com/PRX/proxy.prx.org/commit/98441f73c6e76d18a5a59a2d38ad340561333358
