### ISSUE TITLE
API v2 clients use www.prx.org domain

### ISSUE THREAD

**Issue by farski** [PRX/proxy.prx.org#4]
(Moved from https://github.com/PRX/corporate.prx.org/issues/73)

I believe V1 API goes against api.prx.org, and we can keep that pointed at exchange:
http://api.prx.org/v1/documentation

I believe that would be:
* The moth app(s) for getting list of episodes (this app is retired...)
* wfmt-services app, for creating BN & JN pieces on prx.org
* remix-select app for creating remix select series pieces on prx.org

They all currently use www, not sure how easy to update these, or should we proxy v2 API urls?

Also might just be time to update these, it has been awhile...

**Comment by cavis** [comment]
V2 (and v1) urls are currently being proxied to exchange.prx.org.  Haven't tested it with individual apps, but i don't know why it wouldn't work.

**Comment by cavis** [comment]
Update: apps have been updated to point directly at exchange, since they can't work with api gateway SSL anyways.
