### ISSUE TITLE
Test out PRI.org proxy settings prior to TW Launch

### ISSUE THREAD

**Issue by brandonhundt** [PRX/proxy.prx.org#44]
- [x] Set up proxytest.pri.org DNS record
- [x] Update PRI.org URLs in proxy to proxytext.pri.org
- [x] Ensure 301 redirects are successful

**Comment by farski** [comment]
Things generally appear to be working based on the rules that I currently have.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3483/137915686-2821c702-719c-4f0e-bb25-29c5e1312b63.png">
